runtime: nodejs20
service: data-rempah

env_variables:
  INSTANCE_CONNECTION_NAME: "INSTANCE"
  DB_HOST: "HOST"
  DB_NAME: "DATABASE" # Replace with your DB name
  DB_USER: "USER" # Replace with your DB user
  DB_PASSWORD: "PASSWORD" #add your DB password here

entrypoint: node index.js

handlers:
- url: /.*
  script: auto
